### ISSUE TITLE
example to catch failed login does not work.

### ISSUE THREAD

**Issue by cpasztor** [Actifio/ActPowerCLI-PS7#2]
we are seeing issues with clustered servers initializing ActPowerCLI and the example to catch a failed login attempt does not work.

Name        Version   ModuleBase                                            
----        -------   ----------                                            
ActPowerCLI 10.0.1.34 C:\Program Files\WindowsPowerShell\Modules\ActPowerCLI

PS D:\install\ActPowerCLI-main\ActPowerCLI-main> [System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials

PS D:\install\ActPowerCLI-main\ActPowerCLI-main> $loginattempt = Connect-Act cccc -actuser xxxxxxx -password 'yyyyyyyy' -i -q
$loginattempt
The operation has timed out.

PS D:\install\ActPowerCLI-main\ActPowerCLI-main> $loginattempt

PS D:\install\ActPowerCLI-main\ActPowerCLI-main> if ($loginattempt.errormessage)
{
  write-host "Login failed"
}

PS D:\install\ActPowerCLI-main\ActPowerCLI-main> 

if we can capture the timeout it would immensely stabilize the scripts and is much more elegant than our current workaround which is always connecting twice... and hoping the connection works or having it fail one the next udsinfo / udstask fails.

[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
Connect-Act ccccc -actuser xxxxx -password 'yyyyyy' -i
Connect-Act ccccc -actuser xxxxx -password 'yyyyyy' -i

**Comment by aussiestorblog** [comment]
Fixed in release 10.0.1.35
Timeouts were not being captured correctly due to a syntax issue.      Now timeouts and connection rejects will always throw an actual error.  Also added -timeout setting to allow user configurable timeouts.   Default is 15 seconds but user can set the timeout with connect-act.   Timeout will be 'unset' with disconnect-act.

So here is a syntax example of the error message with timeout specified.

```
PS C:\Windows\system32> connect-act 10.152.0.22 admin password -i -timeout 5

errormessage
------------
No response was received from 10.152.0.22 after 5 seconds


PS C:\Windows\system32>
```
